# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название сервиса')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='Описание сервиса')),
            ],
        ),
    ]
