# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20171115_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='services/photos', verbose_name='Картинка'),
        ),
    ]
