# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='action',
            field=models.CharField(default='', max_length=1000, verbose_name='Действие (отображение на главной странице)'),
        ),
    ]
