# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20171116_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='callmy',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Обращение перед формой обратной связи)'),
        ),
    ]
