# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 07:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_callmy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['action'], 'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description5',
        ),
        migrations.AddField(
            model_name='service',
            name='ico',
            field=models.ImageField(blank=True, default='', upload_to='services/ico', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='service',
            name='pnum',
            field=models.CharField(default='', max_length=20, verbose_name='Порядковый номер)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', max_length=10000, verbose_name='Описание услуги блок 1'),
        ),
    ]
