# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20171207_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['pnum'], 'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
        migrations.AlterField(
            model_name='service',
            name='ico',
            field=models.ImageField(blank=True, default='', upload_to='services/ico', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pnum',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=200, verbose_name='Порядковый номер'),
        ),
    ]
