# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20171207_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ico',
            field=models.CharField(default='', max_length=1000, verbose_name='Иконка  (Выбрать иконку http://fontawesome.io/icons/ и вставить ее название)'),
        ),
    ]
