# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20171207_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='action',
            field=models.CharField(default='', help_text='Так будет отображаться ссылка на главной странице', max_length=1000, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ico',
            field=models.CharField(default='', help_text='Выбрать иконку http://fontawesome.io/icons/ , кликнуть на нее, скопировать ее название и вставить в это поле', max_length=1000, verbose_name='Иконка '),
        ),
    ]
