# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID автомобиля')),
                ('modelcar', models.CharField(choices=[('Rapid', 'Rapid'), ('Octavia', 'Octavia'), ('Superb', 'Superb'), ('Yeti', 'Yeti'), ('Kodiaq', 'Kodiaq')], default='RAPID', max_length=200, verbose_name='Модель')),
                ('complectation', models.CharField(default='Ambition', max_length=60, verbose_name='Комплектация')),
                ('engine', models.CharField(choices=[('1.2', '1.2'), ('1.4', '1.4'), ('1.6', '1.6'), ('1.8', '1.8'), ('2.0', '2.0'), ('2.2', '2.2')], default='1,6', max_length=200, verbose_name='Объем двигателя')),
                ('power', models.CharField(choices=[('90 л/с', '90 л/с'), ('110 л/с', '110 л/с'), ('120 л/с', '120 л/с'), ('125 л/с', '125 л/с'), ('150 л/с', '150 л/с'), ('220 л/с', '220 л/с'), ('230 л/с', '230 л/с'), ('250 л/с', '250 л/с'), ('280 л/с', '280 л/с')], default='90', max_length=200, verbose_name='Мощность двигателя')),
                ('kpp', models.CharField(choices=[('МКПП', 'МКПП'), ('5 МКПП', '5 МКПП'), ('6 МКПП', '6 МКПП'), ('АКПП', 'АКПП'), ('DSG', 'DSG')], default='5МКПП', max_length=200, verbose_name='Коробка передач')),
                ('oldprice', models.CharField(default='', max_length=60, verbose_name='Старая цена')),
                ('newprice', models.CharField(default='', max_length=60, verbose_name='Новая цена')),
                ('image', models.ImageField(help_text='250x172px', upload_to='skoda/files/media', verbose_name='Ссылка картинки')),
            ],
        ),
    ]
