# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20171112_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['modelcar'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(help_text='250x172px', upload_to='cars/photos', verbose_name='Ссылка картинки'),
        ),
    ]
