# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20171112_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default='', max_length=300, verbose_name='e-mail для заявок')),
            ],
        ),
    ]
