# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(default='', max_length=600, verbose_name='Скрипт')),
            ],
            options={
                'verbose_name': 'Скрипт',
                'verbose_name_plural': 'Скрипты',
            },
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Почта для заявок', 'verbose_name_plural': 'Почта для заявок'},
        ),
    ]
