# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20171114_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=200, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='car',
            name='dop',
            field=models.TextField(default='Не установлено', max_length=1500, verbose_name='Дополнительные опции'),
        ),
        migrations.AddField(
            model_name='car',
            name='privod',
            field=models.CharField(choices=[('Передний', 'Передний'), ('Полный', 'Полный')], default='Передний', max_length=200, verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='car',
            name='tipeeng',
            field=models.CharField(choices=[('Бензиновый', 'Бензиновый'), ('Дизельный', 'Дизельный')], default='Бензиновый', max_length=200, verbose_name='Тип двигателя'),
        ),
    ]
