# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20171207_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='vygoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vygodamodelcar', models.CharField(choices=[('Rapid', 'Rapid'), ('Octavia', 'Octavia'), ('Superb', 'Superb'), ('Yeti', 'Yeti'), ('Kodiaq', 'Kodiaq')], default='RAPID', max_length=200, verbose_name='Модель')),
                ('vygoda', models.CharField(default='', max_length=1000, verbose_name='Выгоды на модель')),
            ],
            options={
                'verbose_name': 'Выгода на модель',
                'verbose_name_plural': 'Выгоды на модель',
            },
        ),
    ]
