# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20171207_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vygoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vygoda_Rapid', models.CharField(default='', max_length=1000, verbose_name='Выгоды на Rapid')),
                ('vygoda_Octavia', models.CharField(default='', max_length=1000, verbose_name='Выгоды на Octavia')),
                ('vygoda_Superb', models.CharField(default='', max_length=1000, verbose_name='Выгоды на Superb')),
                ('vygoda_Yeti', models.CharField(default='', max_length=1000, verbose_name='Выгоды на Yeti')),
                ('vygoda_Kodiaq', models.CharField(default='', max_length=1000, verbose_name='Выгоды на Kodiaq')),
            ],
            options={
                'verbose_name': 'Выгода на модель',
                'verbose_name_plural': 'Выгоды на модель',
            },
        ),
        migrations.DeleteModel(
            name='VygodaRapid',
        ),
    ]
