# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20171207_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='VygodaRapid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vygoda', models.CharField(default='', max_length=1000, verbose_name='Выгоды на Rapid')),
            ],
            options={
                'verbose_name': 'Выгода на Rapid',
                'verbose_name_plural': 'Выгода на Rapid',
            },
        ),
        migrations.DeleteModel(
            name='Vygoda',
        ),
    ]
