# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_vygodakodiaq_vygodaoctavia_vygodasuperb_vygodayeti'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bonus',
            field=models.CharField(default='', max_length=300, verbose_name='Бонус'),
        ),
    ]
