# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20171212_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_email', models.CharField(default='', max_length=200, verbose_name='почта')),
                ('id_name', models.CharField(default='', max_length=200, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='idauto',
            field=models.CharField(default='', max_length=200, verbose_name='ID автомобиля в базе'),
        ),
    ]
