# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_order_id_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_car',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_email',
            field=models.CharField(max_length=200, verbose_name='почта'),
        ),
    ]
