# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20171212_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderCar',
        ),
    ]
