# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20171214_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercar',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
