# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_auto_20171214_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ico',
            field=models.ImageField(default='', upload_to='cars/ico', verbose_name='Дополнительная иконка'),
        ),
    ]
