# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
