# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка на автомобиль', 'verbose_name_plural': 'Заявки на автомобиль'},
        ),
        migrations.AlterField(
            model_name='order_service',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID услуги'),
        ),
    ]
